import { StyleSheet } from 'react-native';

export const colors = {
  bg: '#fbf7f0',
  card: '#ffffff',
  text: '#2b2118',
  subtle: '#8a7f72',
  accent: '#e07a3f',
  accentSoft: '#f6e2d3',
  border: '#ece4d8',
  danger: '#c0392b',
  good: '#3f9142',
};

export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: colors.bg },
  container: { flex: 1, padding: 16 },
  header: { fontSize: 28, fontWeight: '800', color: colors.text, marginBottom: 2 },
  subheader: { fontSize: 13, color: colors.subtle, marginBottom: 16 },
  sectionTitle: { fontSize: 16, fontWeight: '700', color: colors.text, marginTop: 18, marginBottom: 8 },
  input: {
    backgroundColor: colors.card,
    borderColor: colors.border,
    borderWidth: 1,
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 15,
    color: colors.text,
  },
  multiline: { minHeight: 92, textAlignVertical: 'top' },
  button: {
    backgroundColor: colors.accent,
    borderRadius: 12,
    paddingVertical: 14,
    alignItems: 'center',
    marginTop: 12,
  },
  buttonText: { color: '#fff', fontWeight: '700', fontSize: 15 },
  buttonGhost: {
    backgroundColor: 'transparent',
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 12,
    paddingVertical: 12,
    alignItems: 'center',
    marginTop: 8,
  },
  buttonGhostText: { color: colors.text, fontWeight: '600' },
  card: {
    backgroundColor: colors.card,
    borderColor: colors.border,
    borderWidth: 1,
    borderRadius: 14,
    padding: 14,
    marginBottom: 10,
  },
  cardTitle: { fontSize: 17, fontWeight: '700', color: colors.text },
  cardMeta: { fontSize: 12, color: colors.subtle, marginTop: 4 },
  row: { flexDirection: 'row', alignItems: 'center' },
  rowBetween: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  ingredientRow: { flexDirection: 'row', alignItems: 'center', marginBottom: 6 },
  badge: {
    alignSelf: 'flex-start',
    backgroundColor: colors.accentSoft,
    borderRadius: 8,
    paddingHorizontal: 8,
    paddingVertical: 3,
    marginBottom: 8,
  },
  badgeText: { color: colors.accent, fontSize: 12, fontWeight: '700' },
  warn: { color: colors.danger, fontSize: 12, marginTop: 2 },
  stepText: { fontSize: 15, color: colors.text, lineHeight: 21 },
  stepNum: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: colors.accentSoft,
    color: colors.accent,
    textAlign: 'center',
    lineHeight: 24,
    fontWeight: '800',
    marginRight: 10,
    fontSize: 13,
    overflow: 'hidden',
  },
  empty: { color: colors.subtle, fontStyle: 'italic', marginTop: 8 },
  stepper: { flexDirection: 'row', alignItems: 'center', gap: 14 },
  stepperBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: colors.accentSoft,
    alignItems: 'center',
    justifyContent: 'center',
  },
  stepperBtnText: { fontSize: 22, color: colors.accent, fontWeight: '800' },
  link: { color: colors.accent, fontWeight: '700' },
});
